# coding = utf-8

city = {
    'Aberdeen, SC': '',
    'Arun, EN': '',
    'Aylesbury, EN': '',
    'Barking and Dagenham, EN': '',
    'Barnet, EN': '',
    'Barnsley, EN': '',
    'Barry, WA': '',
    'Basildon, EN': '',
    'Basingstoke, EN': '',
    'Bath, EN': '',
    'Bedford, EN': '',
    'Bexley, EN': '',
    'Birmingham, EN': '',
    'Bolton, EN': '',
    'Bournemouth, EN': '',
    'Bradford, EN': '',
    'Brent, EN': '',
    'Brighton & Hove, EN': '',
    'Bristol, EN': '',
    'Bromley, EN': '',
    'Bury, EN': '',
    'Calderdale, EN': '',
    'Camden, EN': '',
    'Canterbury, EN': '',
    'Cardiff, WA': '',
    'Central Bedfordshire, EN': '',
    'Charnwood, EN': '',
    'Chelmsford, EN': '',
    'Cheshire East, EN': '',
    'Cheshire West and Chester, EN': '',
    'Colchester, EN': '',
    'Cornwall, EN': '',
    'County Durham, EN': '',
    'Coventry, EN': '',
    'Croydon, EN': '',
    'Derby, EN': '',
    'Doncaster, EN': '',
    'Dudley, EN': '',
    'Dundee, SC': '',
    'Ealing, EN': '',
    'East Kilbride, SC': '',
    'East Riding of Yorkshire, EN': '',
    'Edinburgh, SC': '',
    'Enfield, EN': '',
    'Gateshead, EN': '',
    'Glasgow, SC': '',
    'Greenwich, EN': '',
    'Hackney, EN': '',
    'Hammersmith and Fulham, EN': '',
    'Haringey, EN': '',
    'Harrogate, EN': '',
    'Harrow, EN': '',
    'Havering, EN': '',
    'Herefordshire, EN': '',
    'Hillingdon, EN': '',
    'Hounslow, EN': '',
    'Hull, EN': '',
    'Huntingdonshire, EN': '',
    'Inverness, SC': '',
    'Islington, EN': '',
    'Kensington and Chelsea, EN': '',
    'King\'s Lynn, EN': '',
    'Kingston upon Thames, EN': '',
    'Kirklees, EN': '',
    'Lambeth, EN': '',
    'Leeds, EN': '',
    'Leicester, EN': '',
    'Lewisham, EN': '',
    'Liverpool, EN': '',
    'Livingston, SC': '',
    'London, EN': '',
    'Luton, EN': '',
    'Maidstone, EN': '',
    'Manchester, EN': '',
    'Medway, EN': '',
    'Merton, EN': '',
    'Milton Keynes, EN': '',
    'Neath, WA': '',
    'New Forest, EN': '',
    'Newcastle upon Tyne, EN': '',
    'Newham, EN': '',
    'North East Lincolnshire, EN': '',
    'North Lincolnshire, EN': '',
    'North Somerset, EN': '',
    'North Tyneside, EN': '',
    'Northampton, EN': '',
    'Northumberland, EN': '',
    'Nottingham, EN': '',
    'Oldham, EN': '',
    'Oxford, EN': '',
    'Paisley, SC': '',
    'Peterborough, EN': '',
    'Plymouth, EN': '',
    'Poole, EN': '',
    'Portsmouth, EN': '',
    'Reading, EN': '',
    'Redbridge, EN': '',
    'Richmond upon Thames, EN': '',
    'Rochdale, EN': '',
    'Rotherham, EN': '',
    'Salford, EN': '',
    'Sandwell, EN': '',
    'Sefton, EN': '',
    'Sheffield, EN': '',
    'Shropshire, EN': '',
    'Solihull, EN': '',
    'South Cambridgeshire, EN': '',
    'South Gloucestershire, EN': '',
    'South Somerset, EN': '',
    'South Tyneside, EN': '',
    'Southampton, EN': '',
    'Southend-on-Sea, EN': '',
    'Southwark, EN': '',
    'St Helens, EN': '',
    'Stockport, EN': '',
    'Stockton-on-Tees, EN': '',
    'Stoke-on-Trent, EN': '',
    'Sunderland, EN': '',
    'Sutton, EN': '',
    'Swansea, WA': '',
    'Swindon, EN': '',
    'Tameside, EN': '',
    'Telford and Wrekin, EN': '',
    'Thurrock, EN': '',
    'Tower Hamlets, EN': '',
    'Trafford, EN': '',
    'Wakefield, EN': '',
    'Walsall, EN': '',
    'Waltham Forest, EN': '',
    'Wandsworth, EN': '',
    'Warrington, EN': '',
    'Wealden, EN': '',
    'West Berkshire, EN': '',
    'Westminster, EN': '',
    'Wigan, EN': '',
    'Wiltshire, EN': '',
    'Wirral, EN': '',
    'Wokingham, EN': '',
    'Wolverhampton, EN': '',
    'Wrexham, WA': '',
    'Wycombe, EN': '',
    'York, EN': ''
}